---
repos:
  # https://github.com/pre-commit/pre-commit-hooks/releases
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-executables-have-shebangs

      # - id: trailing-whitespace
      #   args: [--markdown-linebreak-ext=md]
      # - id: end-of-file-fixer
      # - id: check-yaml
      #   args: [--unsafe]
      # - id: check-json
      # - id: check-toml
      # - id: check-xml
      # - id: check-added-large-files
      #   args: [--maxkb=1024]
      # - id: check-case-conflict
      # - id: check-merge-conflict
      # - id: check-symlinks
      # - id: check-vcs-permalinks
      # - id: destroyed-symlinks
      # - id: detect-private-key
      # - id: detect-aws-credentials
      #   args: [--allow-missing-credentials]
      # - id: check-executables-have-shebangs
      # - id: check-shebang-scripts-are-executable
      # - id: mixed-line-ending
      #   args: [--fix=lf]
      # - id: no-commit-to-branch
      #   args: [--branch, main, --branch, master]
      # - id: pretty-format-json
      #   args: [--autofix, --no-sort-keys]
      # - id: fix-byte-order-marker

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        name: yamllint
        description: This hook runs yamllint.
        entry: yamllint
        language: python
        types: [file, yaml]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
        files: ^infrastructure
        args:
          - --args=-recursive

      - id: terragrunt_fmt
        files: ^infrastructure/environments/
        # args:
        #   - --args=-recursive
      # - id: terraform_validate
      #   name: Terraform Validate Core
      #   files: ^terraform/components/core/[^/]+$
      #   args:
      #     - --tf-init-args=-backend-config=environments/backends/nonprod/core.tfbackend
      #     - --tf-init-args=-get=true

      - id: terraform_tflint
        files: ^infrastructure/src
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --args=--call-module-type=local
          - --hook-config=--parallelism-limit=4

      - id: terraform_trivy
        files: ^infrastructure/src
        # args:
        #   - --args=--severity=HIGH,CRITICAL
        #   - --args=--skip-dirs=**/.terraform
        #   - --args=--tf-exclude-downloaded-modules
        args:
          - --args=--config=__GIT_WORKING_DIR__/trivy.yaml

      - id: terragrunt_validate_inputs
        name: Terragrunt validate inputs
        files: ^infrastructure/environments/poc/core/bootstrap/[^/]+$
        # files: ^infrastructure/environments/
        args:
          # Optionally check for unused inputs
          - --args=--terragrunt-strict-validate

      - id: terragrunt_validate
        files: ^infrastructure/environments/poc/core/bootstrap/[^/]+$
        # files: ^infrastructure/environments/
        args:
          - --hook-config=--parallelism-limit=1
      - id: terraform_docs
        files: ^infrastructure/src/
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--recursive
          - --hook-config=--recursive-path=modules
          - --hook-config=--output-file=README.md
          - --hook-config=--output-mode=inject
          - --hook-config=--output-template='<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->'
          - --hook-config=--working-dir=terraform
      - id: terraform_checkov
        files: ^infrastructure/src/
        args:
          - --args=--quiet
          - --args=--config-file __GIT_WORKING_DIR__/.checkov.yaml

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  # Git commit message linting
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
