---
repos:
  # https://github.com/pre-commit/pre-commit-hooks/releases
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master, --branch, develop]


  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        name: yamllint
        description: This hook runs yamllint.
        entry: yamllint
        language: python
        types: [file, yaml]
        files: \.(yml|yaml)$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
        files: ^infrastructure
        args:
          - --args=-recursive

      - id: terragrunt_fmt
        files: ^infrastructure/environments/

      - id: terraform_tflint
        files: ^infrastructure/src
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --args=--call-module-type=local
          - --hook-config=--parallelism-limit=4

      - id: terraform_trivy
        files: ^infrastructure/src
        args:
          - --args=--config=__GIT_WORKING_DIR__/trivy.yaml
          - --args=--skip-dirs=.external_modules

      - id: terragrunt_validate_inputs
        name: Terragrunt validate inputs Bootstrap
        files: ^infrastructure/environments/poc/core/bootstrap/[^/]+$
        args:
          # Optionally check for unused inputs
          - --args=--terragrunt-strict-validate

      - id: terragrunt_validate_inputs
        name: Terragrunt validate inputs Network
        files: ^infrastructure/environments/poc/core/network/[^/]+$
        args:
          # Optionally check for unused inputs
          - --args=--terragrunt-strict-validate

      - id: terragrunt_validate_inputs
        name: Terragrunt validate inputs Shared Services
        files: ^infrastructure/environments/poc/core/shared_services/[^/]+$
        args:
          # Optionally check for unused inputs
          - --args=--terragrunt-strict-validate

      - id: terragrunt_validate_inputs
        name: Terragrunt validate inputs Aurora
        files: ^infrastructure/environments/poc/core/aurora-postgres/[^/]+$
        args:
          # Optionally check for unused inputs
          - --args=--terragrunt-strict-validate

      - id: terragrunt_validate_inputs
        name: Terragrunt validate inputs Lambda Goose Migrator
        files: ^infrastructure/environments/poc/core/lambda-goose-migrator/[^/]+$
        args:
          # Optionally check for unused inputs
          - --args=--terragrunt-strict-validate

      - id: terragrunt_validate_inputs
        name: Terragrunt validate inputs Dev
        files: ^infrastructure/environments/poc/hometest-app/dev/[^/]+$
        args:
          # Optionally check for unused inputs
          - --args=--terragrunt-strict-validate

      # - id: terragrunt_validate
      #   files: ^infrastructure/environments/poc/core/bootstrap/[^/]+$
      #   args:
      #     - --hook-config=--parallelism-limit=1

      - id: terraform_docs
        files: ^infrastructure/src/
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--recursive
          - --hook-config=--recursive-path=modules
          - --hook-config=--output-file=README.md
          - --hook-config=--output-mode=inject
          - --hook-config=--output-template='<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->'
          - --hook-config=--working-dir=terraform

      - id: terraform_checkov
        files: ^infrastructure/src/
        args:
          - --args=--quiet
          - --args=--config-file __GIT_WORKING_DIR__/.checkov.yaml

  # - repo: https://github.com/gitleaks/gitleaks
  #   rev: v8.30.0
  #   hooks:
  #     - id: gitleaks

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        exclude: ^infrastructure/src
        args: [--fix]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.0.4        # pin to a specific version
    hooks:
      - id: sqlfluff-lint
        args: ["--config", ".sqlfluff"]   # optional, if you keep config elsewhere
      - id: sqlfluff-fix
        args: ["--config", ".sqlfluff"]   # auto-fix style issues

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: [--severity=warning]

  - repo: local
    hooks:
      # - id: trivy-fs-scan
      #   name: Trivy filesystem scan
      #   entry: trivy fs --scanners vuln --severity HIGH,CRITICAL --exit-code 1 .
      #   language: system
      #   pass_filenames: false

      - id: gitleaks
        name: gitleaks
        entry: gitleaks detect --no-git --redact --verbose --config=scripts/config/gitleaks.toml
        language: system
        pass_filenames: false
