---
name: "CI/CD deploy"
run-name: "Deploy hometest-mgmt-terraform to env: poc, tf: apply"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # inputs:
    #   hometest_service_ref:
    #     description: "Branch, tag, or SHA to checkout for hometest-service"
    #     required: false
    #     default: "main"

jobs:
  metadata:
    name: "Set CI/CD metadata"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      build_datetime: ${{ steps.variables.outputs.build_datetime }}
      build_timestamp: ${{ steps.variables.outputs.build_timestamp }}
      build_epoch: ${{ steps.variables.outputs.build_epoch }}
      nodejs_version: ${{ steps.variables.outputs.nodejs_version }}
      python_version: ${{ steps.variables.outputs.python_version }}
      terraform_version: ${{ steps.variables.outputs.terraform_version }}
      version: ${{ steps.variables.outputs.version }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: "Set CI/CD variables"
        id: variables
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          {
            echo "build_datetime=$datetime"
            echo "build_timestamp=$(date --date="$datetime" -u +'%Y%m%d%H%M%S')"
            echo "build_epoch=$(date --date="$datetime" -u +'%s')"
            echo "nodejs_version=$(grep "^nodejs\s" .tool-versions | cut -f2 -d' ')"
            echo "python_version=$(grep "^python\s" .tool-versions | cut -f2 -d' ')"
            echo "terraform_version=$(grep "^terraform\s" .tool-versions | cut -f2 -d' ')"
            # TODO: Get the version, but it may not be the .version file as this should come from the CI/CD Pull Request Workflow
            echo "version=$(head -n 1 .version 2> /dev/null || echo unknown)"
          } >> "$GITHUB_OUTPUT"
      - name: "List variables"
        run: |
          export BUILD_DATETIME="${{ steps.variables.outputs.build_datetime }}"
          export BUILD_TIMESTAMP="${{ steps.variables.outputs.build_timestamp }}"
          export BUILD_EPOCH="${{ steps.variables.outputs.build_epoch }}"
          export NODEJS_VERSION="${{ steps.variables.outputs.nodejs_version }}"
          export PYTHON_VERSION="${{ steps.variables.outputs.python_version }}"
          export TERRAFORM_VERSION="${{ steps.variables.outputs.terraform_version }}"
          export VERSION="${{ steps.variables.outputs.version }}"
          make list-variables

  deploy-bootstrap:
    name: "Deploy TF Core/Bootstrap"
    runs-on: ubuntu-latest
    needs: [metadata]
    timeout-minutes: 10
    permissions:
      id-token: write    # REQUIRED for OIDC token
      contents: read     # For checkout
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: Deploy TF Core/Bootstrap
        uses: ./.github/actions/deploy-terragrunt
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          working_directory: infrastructure/environments/poc/core/bootstrap/

  deploy-network:
    name: "Deploy TF Core/Network"
    runs-on: ubuntu-latest
    needs: [deploy-bootstrap]
    timeout-minutes: 10
    permissions:
      id-token: write    # REQUIRED for OIDC token
      contents: read     # For checkout
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: Deploy TF Core/Network
        uses: ./.github/actions/deploy-terragrunt
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          working_directory: infrastructure/environments/poc/core/network/

  deploy-aurora:
    name: "Deploy TF Core/aurora-postgres"
    runs-on: ubuntu-latest
    needs: [deploy-network]
    timeout-minutes: 10
    permissions:
      id-token: write    # REQUIRED for OIDC token
      contents: read     # For checkout
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: Deploy TF Core/aurora-postgres
        uses: ./.github/actions/deploy-terragrunt
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          working_directory: infrastructure/environments/poc/core/aurora-postgres/

  deploy-shared-services:
    name: "Deploy TF Core/shared_services"
    runs-on: ubuntu-latest
    needs: [deploy-aurora]
    timeout-minutes: 10
    permissions:
      id-token: write    # REQUIRED for OIDC token
      contents: read     # For checkout
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6

      - name: Deploy TF Core/shared_services
        uses: ./.github/actions/deploy-terragrunt
        with:
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          working_directory: infrastructure/environments/poc/core/shared_services/

  # deploy-dev:
  #   name: "Deploy TF dev"
  #   runs-on: ubuntu-latest
  #   needs: [deploy-shared-services]
  #   timeout-minutes: 10
  #   permissions:
  #     id-token: write    # REQUIRED for OIDC token
  #     contents: read     # For checkout
  #   steps:
  #     - name: "Checkout code"
  #       uses: actions/checkout@v6
  #       with:
  #         path: hometest-mgmt-terraform

  #     - name: "Checkout hometest-service"
  #       uses: actions/checkout@v6
  #       with:
  #         repository: "NHSDigital/hometest-service"
  #         ref: ${{ inputs.hometest_service_ref }}
  #         path: hometest-service
  #         token: ${{ secrets.NHS_HOMETEST_ORG_PAT }}

  #     - name: "Checkout hometest-mgmt-terraform"
  #       uses: actions/checkout@v6
  #       with:
  #         path: hometest-mgmt-terraform

  #     - name: "Checkout hometest-service"
  #       uses: actions/checkout@v6
  #       with:
  #         repository: "NHSDigital/hometest-service"
  #         ref: ${{ inputs.hometest_service_ref }}
  #         path: hometest-service
  #         ssh-key: ${{ secrets.NHS_HOMETEST_SERVICE_DEPLOY_KEY_SSH_PRIV }}

  #     - name: Deploy TF Dev
  #       uses: ./hometest-mgmt-terraform/.github/actions/deploy-terragrunt
  #       with:
  #         working_directory: hometest-mgmt-terraform/infrastructure/environments/poc/dev/hometest-app
  #         aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}

  # TODO: More jobs or/and steps here
  # success:
  #   name: "Success notification"
  #   runs-on: ubuntu-latest
  #   needs: [deploy]
  #   steps:
  #     - name: "Check prerequisites for notification"
  #       id: check
  #       run: echo "secret_exist=${{ secrets.TEAMS_NOTIFICATION_WEBHOOK_URL != '' }}" >> $GITHUB_OUTPUT
  #     - name: "Notify on deployment to an environment"
  #       if: steps.check.outputs.secret_exist == 'true'
  #       uses: nhs-england-tools/notify-msteams-action@v0.0.4
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         teams-webhook-url: ${{ secrets.TEAMS_NOTIFICATION_WEBHOOK_URL }}
  #         message-title: "Notification title"
  #         message-text: "This is a notification body"
  #         link: ${{ github.event.pull_request.html_url }}
